service: digital-bhaat

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    NODE_ENV: ${opt:stage, 'development'}
    MONGO_URI: ${env:MONGO_URI}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false

functions:
  app:
    handler: handler.handler
    timeout: 30
    events:
      - httpApi:
          path: /{proxy+}
          method: any

package:
  individually: true

build:
  esbuild: true
  sourcemap: true
  minify: false

custom:
  dotenv:
    path: .env.${opt:stage, 'development'}
  serverless-offline:
    httpPort: 4000
    lambdaTimeout: 30

plugins:
  - serverless-offline
